# Generated by Django 5.1.2 on 2024-11-04 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lab_reports/')),
                ('number_of_pages', models.IntegerField(blank=True, null=True)),
                ('extracted_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('experimental_value', models.ImageField(blank=True, null=True, upload_to='')),
                ('answer', models.TextField()),
                ('lab_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.labreport')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('lab_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.labreport')),
            ],
        ),
    ]
